# Generated by Django 5.1.6 on 2025-02-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_remove_group_admins_remove_group_invite_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessages',
            old_name='mesages',
            new_name='text_content',
        ),
    ]
