# Generated by Django 5.1.6 on 2025-02-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_chatuser_is_online_group_online_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulsechatusers',
            old_name='status',
            new_name='is_online',
        ),
        migrations.RemoveField(
            model_name='chatuser',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='pulsechatusers',
            name='blocked_users',
        ),
        migrations.RemoveField(
            model_name='pulsechatusers',
            name='contacts',
        ),
    ]
