# Generated by Django 5.1.6 on 2025-02-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_rename_status_pulsechatusers_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsechatusers',
            name='bio',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.DeleteModel(
            name='ChatUser',
        ),
    ]
